version: '3.8'

services:
  steam-hour-boost:
    build: .
    image: cs2central/steam-hour-boost:1.1.0
    container_name: steam-hour-boost
    restart: unless-stopped
    ports:
      - "8869:8869"
    volumes:
      - steam-hour-boost-data:/data

volumes:
  steam-hour-boost-data:
